version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "3002:3002"
    # depends_on:
    #   - db # If you have a database, uncomment this line
  spa:
    build: ./spa
    ports:
      - "3000:3000"
    depends_on:
      - api # Start the API before the React app

  # Uncomment if you're using a database
  # db:
  #   image: postgres:latest # Or your preferred database
  #   environment:
  #     POSTGRES_USER: your_db_user
  #     POSTGRES_PASSWORD: your_db_password
  #     POSTGRES_DB: your_db_name
