version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "3002:3002"
    depends_on:
      - db
  # spa:
  #   build: ./spa
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api # Start the API before the React app

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: foo # Set root user
      MONGO_INITDB_ROOT_PASSWORD: bar # Set root password
      MONGO_INITDB_DATABASE: taskmanager # Create initial database (optional)
    ports:
      - "27017:27017" # Expose MongoDB port
